framework:
    validation:
        enabled: true
        mapping:
            paths:
                - '%kernel.project_dir%/config/validator'
        auto_mapping:
            App\Entity\: []

when@test:
    framework:
        validation:
            not_compromised_password: false
